GET http://localhost:4004/odata/Employees
###

DELETE http://localhost:4004/odata/Employees('guid ac1cab06-9176-4812-a7fe-f0c7e4d0716'4)

###

POST http://localhost:4004/odata/Employees
Content-Type: application/json

{
      "FIRST_NAME": "Bhavesh",
      "LAST_NAME": "Tiwari",
      "GENDER": "Male",
      "EMAIL": "tiwaribhavesh45@gmail.com.com",
      "EXPERIENCE":3,
      "DESIGNATION":"SAP UI5 & Fiori Consultant",
      "MODULE":"SAP UI5 & Fiori",
      "MODULE_TYPE":"Technical",
      "PHONE_NO": 1234567890,
      "QR_CODE": ""
      
}

###

GET http://localhost:4004/odata/PunchingDetails

###

POST http://localhost:4004/odata/Punch
Content-Type: application/json

{
    "Action":"IN",
    "EmpId":3
}

###

GET http://localhost:4004/odata/Leaves

###

POST http://localhost:4004/odata/PunchingDetails
Content-Type: application/json

{
    "EMP_CODE_EMP_ID":1,
    "PUNCH_DATE":"4/1/2025",
    "PUNCH_IN":"10:05:44",
    "PUNCH_OUT":""
}

###

GET http://localhost:4004/odata/EmployeePunchingDetails

###

GET http://localhost:4004/odata/LeaveRequests

###

POST http://localhost:4004/odata/LeaveRequests
Content-Type: application/json

{
    "APPLIED_BY_EMP_ID":"42d5959d-4f3d-4c69-b0bb-a91ceb1446fe",
    "FROM_DATE":"Jan 27, 2025",
    "TO_DATE":"Jan 28, 2025",
    "PRIORITY":"High",
    "TYPE":"Sick Leave",
    "REASON":"Hospital visit for eye check up",
    "STATUS":""
}

###
DELETE http://localhost:4004/odata/LeaveRequests('e52468b1-8931-429d-838f-ae298b5ef6a9')

###

POST http://localhost:4004/odata/ApproveLeave
Content-Type: application/json

{
    "LeaveRequestId":"b3199732-a902-4650-8910-b0322b3caa8f",
    "LeaveType":"Sick Leave",
    "EmpId":"42d5959d-4f3d-4c69-b0bb-a91ceb1446fe"
}

###

POST http://localhost:4004/odata/RejectLeave
Content-Type: application/json

{
    "LeaveRequestId":"7a6a8fc0-c16c-497c-8a36-dcb3c37ffcd9",
    "LeaveType":"Casual Leave",
    "EmpId":"42d5959d-4f3d-4c69-b0bb-a91ceb1446fe"
}

###


GET http://localhost:4004/odata/LeaveBalances

###

POST http://localhost:4004/odata/LeaveBalances
Content-Type: application/json

{
    "TOTAL_LEAVE_COUNT":30,
    "AVAILABLE_LEAVE_COUNT":28,
    "EMP_EMP_ID":"2c0d855c-8979-4995-a36c-07bfca29a093"
}

###

DELETE  http://localhost:4004/odata/LeaveBalances('ee337641-f98a-493f-8ef1-a1976c5e7d8f')

###

GET http://localhost:4004/odata/GetLoggedInUser(Email='tiwaribhavesh45@gmail.com')